deepomatic/dmake/core.py

App build may generate files or directories only readable by root, in
which case dmake fails early:
```
Traceback (most recent call last):
File "/home/thomas/deepomatic/dmake/deepomatic/dmake/dmake", line 73, in <module>
core.make(root_dir, sub_dir, command, app, options)
File "/home/thomas/deepomatic/dmake/deepomatic/dmake/core.py", line 495, in make
build_files = load_dmake_files_list()
File "/home/thomas/deepomatic/dmake/deepomatic/dmake/core.py", line 93, in load_dmake_files_list
build_files = common.run_shell_command("find . -name dmake.yml").split("\n")
File "/home/thomas/deepomatic/dmake/deepomatic/dmake/common.py", line 33, in run_shell_command
raise ShellError(stderr)
deepomatic.dmake.common.ShellError: find: ‘./buffers/generated/python/buffers/flatbuf’: Permission denied
``` …

More robust finding of dmake.yml files

---

deepomatic/dmake/common.py
deepomatic/dmake/python_2x.py
deepomatic/dmake/python_3x.py

With python2 `run_shell_command` previously failed to raise
`ShellError(stderr.decode())` in case of error:
```
Traceback (most recent call last):
File "/home/thomas/deepomatic/dmake/deepomatic/dmake/dmake", line 73, in <module>
core.make(root_dir, sub_dir, command, app, options)
File "/home/thomas/deepomatic/dmake/deepomatic/dmake/core.py", line 495, in make
build_files = load_dmake_files_list()
File "/home/thomas/deepomatic/dmake/deepomatic/dmake/core.py", line 93, in load_dmake_files_list
build_files = common.run_shell_command("find . -name dmake.yml").split("\n")
File "/home/thomas/deepomatic/dmake/deepomatic/dmake/common.py", line 33, in run_shell_command
raise ShellError(stderr.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in …
```

Fix python2 string decoding issue on stderr ShellException

---

deepomatic/dmake/core.py

The purpose of 'run' command is to launch dockers, thus we should not trigger a cleaning at the end of dmake, otherwise they would be removed. 
A better way should be to clean the temporary directory only, without removing the docker but this is more work and not really critical.

Avoid cleaning docker images for the 'run' command

---

deepomatic/dmake/common.py
deepomatic/dmake/deepobuild.py

Closes #28 
**do not merge yet** 
`.build.env` is for images build; `.env` is for runtime
environment (contains external services, secrets).
New dmake.yml root `build.env` usage: a simple dict defining
environment variables for all service builds.
Build environment should be the same for testing and deployment, for
the tests to be meaningful.
However, debug builds with coverage are useful too for development/PR.
New DMake-generated env var for all builds:
`DMAKE_BUILD_ENV={release,testing}`, set to `release` if the current
branch is for releases (currently defined as: having a deploy stage
for any service for any dmake.yml file in the repo).
Other build env vars should be local to the machine building the app,
not specializing the built image for different usages.
Remarks:
* Env values …

Cleaner separation between build and run environment variables: `build.env`

---

deepomatic/dmake/deepobuild.py
deepomatic/dmake/kubernetes.py
deepomatic/dmake/utils/dmake_deploy_k8s_cd
requirements.txt

Closes #46 
* Pass runtime env to k8s_deployment using ConfigMap
* Add a dmake metadata ConfigMap defining service current ConfigMap env name and image.

Pass runtime env in k8s_cd

---

deepomatic/dmake/utils/dmake_deploy_k8s_cd

This helps for migrations to new clusters.

In k8s_cd, always create the ConfigMaps, even if no deployment is found.

---

deepomatic/dmake/core.py
deepomatic/dmake/deepobuild.py
deepomatic/dmake/docker_registry.py
deepomatic/dmake/utils/dmake_build_base_docker
deepomatic/dmake/utils/dmake_deploy_kubernetes
requirements.txt

Closes #35 
Better base image caching: docker tag derived from sources hash
* base_image name: `.docker.base_image.name`
* base_image tag: `base-rid-$(root image digest| tr : -)-dd-$(dmake md5s file | md5)`
* rid: root image digest: docker image digest (`sha256:...`)
* dd: dmake digest (short for dmake base image build scripts digest):
an id representing all the sources used to build the base_image on
top of the root image digest: `$(md5sum md5s | cut -d' ' -f1)`
The base_image tag is now purely dependent on its source definition:
it can even factorize builds if 2 dmake.yml describe the same
base_image.
Also, `.docker.base_image.version` is not used anymore, keeping it for now to
avoid breaking all `dmake.yml` files.

Better base image caching: docker tag derived from sources hash

---

deepomatic/dmake/deepobuild.py

If we already have decided we are on a release branch, then stop
searching for that on other `dmake.yml` files.

Avoid searching for release branch and print multiple times

---

deepomatic/dmake/common.py
deepomatic/dmake/docker_config.py
deepomatic/dmake/docker_registry.py
requirements.txt

Closes #53
Parse more auth variants from docker config file: support credsStore and credHelpers
Now support these config:
* `base`:
```
{
"auths": {
"https://index.docker.io/v1/": {
"auth": "foobar="
}
}
}
```
* `credsStore`:
```
{
"auths": {
"https://index.docker.io/v1/": {}
},
"credsStore": "osxkeychain"
}
```
* `credHelpers`:
```
{
"auths": {
"https://index.docker.io/v1/": {}
},
"credHelpers": {
"https://index.docker.io/v1/": "secretservice"
}
}
```

Docker credential store

---

deepomatic/dmake/common.py

On github both urls (with and without `.git` suffix) are valid.

Allow git origin without trailing `.git`.

---

.dockerignore

When building the docker images it now ignores:
* .git dir
* dmake files
It's safer (no secrets from dmake files in build context), and faster.

Add a .dockerignore

---

deepomatic/dmake/utils/dmake_build_base_docker

trap doesn't change the global return code, no need for explicit
exit (and the exit in trap was wrong: it masked the real return code
by returning the `rm` return code).

Fix dmake_build_base_docker return code in case of error

---

deepomatic/dmake/core.py

New output:
```
Generating commands...
Output has been written to /tmp/dmake_tmp_xxx/DMakefile
- Running base @ deepomatic/xxx::base
Checking cache for docker base image (deepomatic/xxx)
Docker base image found in cache, using it (deepomatic/xxx)
- Running run_link @ links/vesta/rabbitmq
3.6-management: Pulling from library/rabbitmq
Digest: sha256:xxx
Status: Image is up to date for rabbitmq:3.6-management
dmake_wait_for_it: waiting 30 seconds for 172.17.0.2:5672
dmake_wait_for_it: 172.17.0.2:5672 is available after 6 seconds
- Running run_link @ links/vesta/db
9.6: Pulling from library/postgres
Digest: sha256:xxx
Status: Image is up to date for postgres:9.6
dmake_wait_for_it: waiting 30 seconds for 172.17.0.3:5432
dmake_wait_for_it: 172.17.0.3:5432 is available after 0 seconds
- Running …
```

More readable stage and steps logs for bash execution.

---

deepomatic/dmake/deepobuild.py

`dmake run` previously generated duplicated docker options such as
ports.
Regression introduced by 079cd449e340943f4ce8e1769db5c360ac00558b.
Fixed by removing duplicate calls to `full_docker_opts`:
- once in `opts` from `_launch_options_`: kept
- once in `generate_run` directly: removed

Fix duplicated docker options.

---

deepomatic/dmake/core.py

`dmake stop` should stop containers started by `dmake start`.
It previously failed because it searched wrong container names.
The run_daemon is called with empty name, and auto generated names have
`repo.branch.build` as prefix: using that to stop containers.

Fix dmake stop

---

deepomatic/dmake/deepobuild.py

Previously it was a path relative to repo root directory, but the
newer "dir" type broke that by checking its existence relative to
current dmake.yml directory.
No project seem to have broken (it is not used), so keeping new "dir"
type semantic to be more coherent.

Fix `copy_directories`: it's now a path relative to current dmake.yml irectory, as imposed by the "dir" type.

---

deepomatic/dmake/utils/dmake_build_base_docker

By default `docker commit` takes the latest cmd as CMD:
/base_volume/make_base.sh. This doesn't exist after the build, so it
makes no sense to keep that. It just disturbs manual users of the base
image (for debug).

Change CMD of base image: /bin/bash

---

deepomatic/dmake/deepobuild.py
deepomatic/dmake/utils/dmake_run_docker

`need_gpu` was previously only supported on SSH deployments; now it is
also supported for local operations: `shell`, `test` and `run`.
It requires `nvidia-docker` (as in the SSH deployment).
It doesn't apply to build step (because it doesn't make sense), nor for now to run_links (`docker_links`), external dependencies for test, as we don't have `need_gpu` option for them yet.

Add support for GPU in shell, test and run

---

deepomatic/dmake/core.py
deepomatic/dmake/deepobuild.py

Let links export their environment variables to avoid hacking them in an entrypoint.

Let links export their environment variables

---

deepomatic/dmake/templates/deploy/deploy_ssh/start_app.sh

It is retro-compatible thanks to a `nvidia-docker` shell wrapper.
We should later drop the usage of `nvidia-docker` itself at is is not
needed anymore.
`nvidia-docker` v2 installation doc: https://github.com/NVIDIA/nvidia-docker/tree/2.0#installation
Only potential issue: installing this overwrites `/etc/docker/daemon.json`. Luckily we don't change that in production servers.

 SSH deployment: Install nvidia-docker v2 instead of v1.

---

deepomatic/dmake/common.py
deepomatic/dmake/deepobuild.py

Used and changed semantic for `common.run_shell_command`
`raise_on_return_code`: now it raises an error *only* on non-zero
return code.
Previously it also returned an error if stderr is non-empty, which
makes no sense, but is kept for backward compatibility.
stderr warning example:
```
W1205 16:54:23.957959   14961 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
```

`kubectl` fails on error only when it returns a non-zero return code

---

deepomatic/dmake/deepobuild.py
deepomatic/dmake/utils/dmake_run_docker

This reverts commit c02e06ce06ab75b3434063ff9979b12273213710.
For local GPU use, install nvidia-docker v2 and configure it as
default docker runtime engine. This will make all docker images
inheriting nvidia ones working; which is currently the case for all
usages.
Later we should re-add explicit usage with the `--runtime=nvidia`
option alongside `NVIDIA_*` environment variables.

Revert "Add support for GPU in shell, test and run (#72)"

---

deepomatic/dmake/deepobuild.py

Needed service env used to be evaluated irrespective of variables exported by links, which led to wrong variable replacement.

Evaluate needed service env in context

---

deepomatic/dmake/common.py
deepomatic/dmake/core.py
deepomatic/dmake/deepobuild.py
deepomatic/dmake/templates/deploy/deploy_ssh/start_app.sh
deepomatic/dmake/utils/dmake_run_docker_test
deepomatic/dmake/utils/dmake_test_get_results
tutorial/web/app/tests.py
tutorial/web/dmake.yml
tutorial/web/requirements.txt
tutorial/web/web/settings.py

Closes #34
Pros:
- test production/official service docker image instead of a parallel
build (without install step)
- avoid duplicate build
- avoid writing build files in host workspace
- allows parallel build
Cons:
- need to ship tests programs (and its dependencies) in official image
TODO:

Execute tests using service docker image, not base docker image.

---

deepomatic/dmake/common.py
deepomatic/dmake/core.py
deepomatic/dmake/deepobuild.py
deepomatic/dmake/templates/deploy/deploy_ssh/start_app.sh
deepomatic/dmake/utils/dmake_run_docker_test
deepomatic/dmake/utils/dmake_test_get_results
tutorial/web/app/tests.py
tutorial/web/app/views.py
tutorial/web/dmake.yml
tutorial/web/requirements.txt
tutorial/web/web/settings.py
tutorial/worker/deploy/dependencies.sh
tutorial/worker/dmake.yml
tutorial/worker/src/amqp_client.cpp
tutorial/worker/src/amqp_client.hpp

Closes #75 
Support multiple base image variants per `dmake.yml`, and support multiple base image variants per service (a.k.a service variants).
Work:

Multi base image

---

deepomatic/dmake/utils/dmake_copy

`cp -r` is a bad practice on MacOS, please use `cp -R`

Fix copy on MacOS

---

deepomatic/dmake/utils/dmake_build_base_docker

Closes #120 
Some root images have an entrypoint not compatible with a shell, so we
override it with /bin/bash.
Example with nvidia/digits with `ENTRYPOINT ["python", "-m", "digits"]`:
```
$ docker run --rm nvidia/digits:latest echo ok
usage: __main__.py [-h] [-p PORT] [-d] [--version]
__main__.py: error: unrecognized arguments: echo ok
$ docker run --rm --entrypoint /bin/bash nvidia/digits:latest -c "echo ok"
ok
```

Support root images with non-shell entrypoint

---

deepomatic/dmake/deepobuild.py

Fix #124 .
For the tests we don't want persistence of data.
If volumes are needed for sharing between services, then use raw `testing_options`.

Fix `docker_links` volume non-persistence during tests.

---

deepomatic/dmake/utils/dmake_deploy_kubernetes

Fix #127 
It's broken with kubectl 1.7 and kubernetes master 1.8.

kubernetes deployment: Stop using slash in kubectl annotate

---

deepomatic/dmake/utils/dmake_deploy_kubernetes

Fix #127 
It's completel broken (see https://github.com/Deepomatic/dmake/issues/127#issuecomment-362257409)
Also revert "kubernetes deployment: Stop using slash in kubectl annotate (#128)"
This reverts commit c7a3eaa9d7bd47202ff77bb8716e2f86fe3ca78c.

kubernetes deployment: Disabling the whole kubectl annotate

---

deepomatic/dmake/deepobuild.py

Previously it was only mounted during test and shell on the service,
but we need a quick way to declare volumes to share between services
that are started with run.

Mount tests.data_volumes when service is run too

---

deepomatic/dmake/common.py

`git rev-parse --show-toplevel` stops at first git repository, even if
it's a submodule of a parent repository.
This changes the path where the service is copied into the built
service container when running dmake from a submodule directory:
subtly breaking things (start script path and others are broken).
Could use `git rev-parse --show-superproject-working-tree` to check if
submodule, but only available since git 2.13 (2017-04), not available
by default on ubuntu 16.04.
Revert part of 8080b3fb602d1a0aa33f174ca0d0967840305b46

Fix dmake execution from a submodule directory.

---

deepomatic/dmake/utils/dmake_deploy_k8s_cd

Previously it returned as soon as one replica was up: it could be an
old replica still there because of race condition, or because
replicas>1 and the rollout is one by one.
Now we check if `status.updated_replicas == spec.replicas`:
- `status.updated_replicas` is the number of available replicas that
match the current spec (i.e. are up and their definition is
up-to-date)
- it tolerates concurrent PATCH: we check if it converged to the
current desired state, not the one we initially asked.
We also avoid race conditions where the `status` is not yet updated
with: `status.observed_generation >= generation`, where `generation`
is the Deployment `generation` from the `PATCH` command.
Also added more logging, with timestamps.

Fix Deployment rollout status check

---

Jenkinsfile
deepomatic/dmake/common.py
deepomatic/dmake/deepobuild.py

Add optional template variables for kubernetes deployment manifest
Usage:
- in `dmake.yml`:
```
env:
branches:
default:
variables:
K8S_DEPLOY_TLS_SECRET_NAME: dev-tls-secret
master:
variables:
K8S_DEPLOY_TLS_SECRET_NAME: prod-tls-secret
...
services:
- deploy:
stages:
- kubernetes:
manifest:
template: deploy/kubernetes-deploy.yaml
variables:
TLS_SECRET_NAME: ${K8S_DEPLOY_TLS_SECRET_NAME}
```
- in `deploy/kubernetes-deploy.yaml`:
```
apiVersion: extensions/v1beta1
kind: Ingress
...
spec:
tls:
- secretName: ${TLS_SECRET_NAME}
backend:
serviceName: web
servicePort: 80
```
Still support the simple version where
`services[].deploy.stages[].kubernetes.manifest` is directly a file
path to the manifest.
Also add optional strict mode for `common.eval_str_in_env`: raise error when using undefined …

Add variables to k8s deploy template manifest

---

deepomatic/dmake/common.py
deepomatic/dmake/deepobuild.py
deepomatic/dmake/utils/dmake_run_docker

Closes #140 
- added `need_gpu` on `docker_links[]` (in addition to previous
`services[].config`)
- use `need_gpu` on local executions: run, run_link, test, shell
(in addition to previous ssh deploy)
Locally we now use nvidia docker v2 with:
`docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all`
This allows using GPU on any docker image (not just `FROM
nvidia/cuda`).
If local machine doesn't support nvidia docker v2, then GPU support
can be disabled with `export DMAKE_NO_GPU=1`: the services will be run
without GPU, it could break things: it's the user's responsibility.

Support `need_gpu` on all services, for all local executions.

---

deepomatic/dmake/common.py
deepomatic/dmake/core.py
deepomatic/dmake/deepobuild.py

Closes #142 
In practice it wraps the whole `Testing App` stage with a
`lock('GPU'){...}` block if any used service (app or docker_link)
requested a gpu via `need_gpu`.
Limitations:
- `dmake shell` is not supported: it is currently split into the
`Deploy` stage instead of `Testing App`, so it's harder to include it
in the lock, and `dmake shell` is never used with the Jenkins pipeline
mode anyway.
- locking is not minimal: we lock the whole testing stage instead of
just when services needing a GPU are up; but it doesn't change much:
we currently have only optimal service start, not service stop, so we
would not gain much. Also, services dependencies are recursive, so we
often need the GPU the whole time anyway.

Add a Jenkins lock on 'GPU' when testing services that need one

---

deepomatic/dmake/common.py
deepomatic/dmake/core.py
deepomatic/dmake/deepobuild.py
deepomatic/dmake/utils/dmake_create_docker_shared_volume
deepomatic/dmake/utils/dmake_remove_docker_containers_and_images
tutorial/web/deploy/test-shared-volumes.sh
tutorial/web/dmake.yml
tutorial/worker/deploy/test-shared-volumes.sh
tutorial/worker/dmake.yml

Closes #135 
They can be used during the dmake session in any service (app service
or docker_link service).
They are deleted at the end of the dmake session.
Permissions in the create volumes are set to
`${DMAKE_UID}:${DMAKE_UID}` so app services can write; it may require
manual handling for permissions with `docker_link` services.
Usage:
=====
- `services[].config.volumes` now accept named shared volumes
In addition to object {container_volume, host_volume}, it now accepts
a string value: `<volume_name>:<container_path>`
The `<volume_name>` is the name of a shared volume declared in root
`volumes`.
- `docker_link[].volumes` now also accepts named shared volumes
In addition to `<host_path>:<container_path>` (which is still only
applied for shell, because we don't want persistence during …

Add `volumes` at dmake.yml root: declare shared volumes by name

---

deepomatic/dmake/common.py
deepomatic/dmake/deepobuild.py

(and other functions that use the same sub-functions)
Closes #145 
We previously evaluated 2 or 3 times the same env, and mixed
evaluation, additional envs, context env...
Now runtime env is computed once (in `_launch_options_()`), with
correct additional customization variables; and is passed up to all
others functions that could need it, to evaluate values elsewhere, and
to send the env to the containers.
- `context_env` is the same as `env`: the runtime env
- `customized_env` is in fact `additional_customization_variables`
- everything is evalualuated using the one runtime `env`
Bug fixes/behavior change:
- in `dmake shell` the `.build.env` values were previously wrongly
evaluated in the runtime `.env` context. Now they are just evaluated
from the dmake process environment (that was …

Cleanup `env` mess in generate_run

---

deepomatic/dmake/common.py
deepomatic/dmake/deepobuild.py
deepomatic/dmake/kubernetes.py
deepomatic/dmake/serializer.py
deepomatic/dmake/utils/dmake_deploy_kubernetes

Add pruning to kubernetes deployment
Previously when removing a resource it leaked in the cluster, because
`kubectl apply` cannot know for sure what to remove.
The way to do it is to explicitly ask for pruning, and limit scope to
some resources via label selectors.
For it to work, we need to
- set a specific label to all resources (top level only because
cascading handles that (e.g. Deploy -> RC -> Pod)), that
scopes to the current dmake deployment: dmake app service_name:
`dmake.deepomatic.com/service=<app>-<service_name>`
(later it could be changed to deployment, when we add the concept of
deployment independent of dmake service; the transition may be hard
though.)
- and select on that when pruning (and when applying: both
are done at the same time and both are impacted by the label …

K8s deploy prune

---

deepomatic/dmake/deepobuild.py
deepomatic/dmake/serializer.py
deepomatic/dmake/utils/dmake_build_docker
tutorial/worker/.dockerignore
tutorial/worker/Dockerfile
tutorial/worker/Makefile
tutorial/worker/dmake.yml

Closes #139 
Add `build` to `.services[].config.docker_image`, subset of Docker
Compose `build` format.
`build` can take 2 forms:
- string: docker build context directory, relative to current
`dmake.yml` file
- object:
- `context`: docker build context directory, relative to current
`dmake.yml` file
- `dockerfile`: Alternate `Dockerfile`, relative to `context`
directory
- `args`: dictionary of docker build arguments
- `labels`: dictionary of labels to add to the built image
Examples:
========
```
build: .
```
```
build:
context: ./app
dockerfile: deploy/Dockerfile
args:
BUILD_HOST: ${HOSTNAME}
labels:
vendor: deepomatic
```
More: see `tutorial/worker/dmake.yml`
Details:
=======
- when using user-provided Dockerfile for service docker image build,
all other build related options are …

Optionally build services with user-provided Dockerfile

---

dmake/core.py
dmake/deepobuild.py
dmake/utils/dmake_return_docker_links
dmake/utils/dmake_run_docker
dmake/utils/dmake_run_docker_daemon
dmake/utils/dmake_run_docker_link
tutorial/web/deploy/dependencies.sh
tutorial/web/deploy/test-needed-service-link.sh
tutorial/web/deploy/test-shared-volumes.sh
tutorial/web/dmake.yml
tutorial/worker/deploy/start.sh
tutorial/worker/deploy/test-shared-volumes.sh
tutorial/worker/dmake.yml

Closes #165 
When `link_name` is set, the needed service will be exposed to the dependent service
using docker links via `link_name` hostname, like with `needed_links`.
Details:
- pass new link_name to dmake_run_docker_daemon
- add needed_services link_names to docker links list
Easiest implementation for now: handle different link_name as
different needed_services; later we should try to aggregate various
link_names to one instance of NeededServiceSerializer in
`service_customization`.
Also some cleanup/fix/refactor:
- Cleanup/fix shared volumes tests in tutorials 
￼- More debug logs on NeededServices
- Cleanup/simplify docker_links runtime
- Refactor dmake_run_docker_link/dmake_run_daemon
- Add optional `link_name` to `needed_services` ￼
- Add needed_services link_name test in tutorial/

Add optional `link_name` to `needed_services`

---

dmake/core.py
dmake/deepobuild.py
dmake/serializer.py
tutorial/e2e/.dockerignore
tutorial/e2e/deploy/Dockerfile
tutorial/e2e/dmake.yml
tutorial/web/dmake.yml

Base images used to not be needed for simple use cases. This fixes a crash due to a bad dependency.

Removing dependancy on base when no base image is provided

---

Jenkinsfile
dmake/common.py
dmake/deepobuild.py
dmake/templates/jenkins/Jenkinsfile
tutorial/worker/dmake.yml

Closes #178
* service docker_image.build: variable substitution for labels in addition to args
Useful to pass custom build args via environment variables.
Also applied "strict" mode on both `args` and `labels`: they are new
options, we should always use "strict" for new options.
"strict" mode raises an error if an undefined variable is used, or if
an error happens during evaluation.
If you want to allow an undefined variable, then use `${MY_VAR:-}`; it
will evaluate to empty string (we have no way to unset...).
Evaluation is done at serialization time: only if the service is
really built, so it should not be too cumbersome to use.
* Add CUSTOM_BUILD_* parameters in Jenkins builds
Used for manual builds of on-premises images with special build args
and labels.

Jenkins Parameters for custom builds, evaluated for build args and labels

---

dmake/deepobuild.py
dmake/utils/dmake_build_docker
tutorial/worker/dmake.yml

This permits re-using the same `Dockerfile` between multiple
services: factorize Dockerfile code, and better use of docker build
cache.
Example: prod with source, and on-premises without source.
Also extended DMAKE_DEBUG to call docker build with `--debug`. It
shows the ignored files via `.dockeringore`.

Add docker multi-stage build target

---

install.sh

This allow the automatic installation of dmake without asking questions for all system user with something like:
```
cd /home; for USER in `ls`; do su $USER -c "/usr/local/dmake/install.sh --non-interactive"; done
```

Add a non-interactive mode in install

---

dmake/utils/dmake_find

Closes #226.
Previous IO redirection was broken and accidentally applied to the
debug traces.
Before:
- swap stderr and stdout for `find`
- redirected `find` stdout is filtered by `grep`
- `grep` stdout is redirected back to line-global stderr
- line-global stderr is redirected to stdout <-- here we include
`set -x` traces
in stdout
After:
- `find` stdout redirected to fd `3`
- `find` stderr redirected to stdout
- redirected `find` stdout is filtered by `grep`
- `grep` stdout is redirected back to line-global stderr
- redirect fd `3` to line-global stdout
=> We never redirect fd `2` (which sometimes includes debug traces)
somewhere else, except for `find` stderr (which does *not* include
debug traces, just `find` stderr).
Previous version was OK when initially added by #21 because it was …

Don't pollute `find` output with debug traces

---

dmake/deepobuild.py
dmake/utils/dmake_build_base_docker
dmake/utils/dmake_md5

Closes #227.
The initial dmake digest (v1, `dd`) had several issues:
- `dmake_md5 /dir` output depended on the order in which `find .`
returns files: it's the directories entries order: not
deterministic (it's generally stable on a given machine, but may
differ across machines). This happens only when
base_image.copy_files array contains a directory.
=> same sources would give different digests: inefficient use of
the cache.
- `dmake_md5` excluded filenames when computing md5 of md5 list of all
files: a renamed file would result in the same digest.
=> different sources could give same digest: break cache mechanism.
This commit adds `dmake digest v2` (`d2` for short (same length as
`dd`, good for docker tag):
- continue to create the base image source in DMAKE_TMP subdir
- simply call …

Introduce dmake digest v2 to base_image cache index

---

dmake/kubernetes.py

Fix this error when dmake is run with python3:
```
TypeError: Unicode-objects must be encoded before hashing
```
We did not catch this issue earlier because of #232

Fix python3 kubernetes env hash

---

dmake/common.py
dmake/docker_registry.py
dmake/python_2x.py
dmake/python_3x.py

Closes #229 
If multiple services uses the same root_image, then only one docker
registry lookup will be done if dmake is run with python3.

Cache get root image digest in python3

---

dmake/core.py

Related to #243
Previously with `dmake test -d '*'` we did not guarantee steps order
between running a service as a dependency of another, and testing that
service.
This resulted in unwanted parallel execution of tests and run as
dependency.
Quickfix: always force testing a service before running it in test
mode (commands `test` and `deploy`).
Drawbacks:
- hardcoded `test` mode, we could use the dependency DAG to know if we
are in test mode instead
- when testing a service instead of `*`, we now also test its
dependencies services.

Quickfix: in test mode, always test dependencies before running them

---

dmake/deepobuild.py
test/worker/dmake.yml
tutorial/worker/dmake.yml

Closes #246 
For now only provides a `dmake shell`-dedicated entrypoint, that won't
leak into the service.
If entrypoints are defined both in service and in dev conf, the dev
conf takes precedence. If needed, we could later try to chain
both entrypoints.
Later we could have a `start_script` for dev (with auto
reload/rebuild) to start multiple services in development mode at the
same time (with service sources mounted from host into container).

Add `dev` for development runtime configuration: `dmake shell`

---

dmake/common.py
dmake/core.py
dmake/dmake
requirements.txt

```
--debug-graph         Generate dmake steps DOT graph for debug purposes.
--debug-graph-and-exit
Generate dmake steps DOT graph for debug purposes then
exit.
--debug-graph-output-filename DEBUG_GRAPH_OUTPUT_FILENAME
The generated DOT graph filename.
--debug-graph-output-format DEBUG_GRAPH_OUTPUT_FORMAT
The generated DOT graph format (`png`, `svg`, `pdf`,
...).
```
```
$ dmake --debug-graph-and-exit --debug-graph-output-format=svg test '*'
===============
REPO : dmake
BUILD : 0
BRANCH : dev-debug_graph
COMMIT_ID : 2c980c5
===============
Forcing full re-build
Generated debug DOT graph: 'dmake-services.gv' and 'dmake-services.gv.svg'
Exiting after debug graph generation
```
debug dmake itself.

Add --debug-graph global option: generate DOT graph of internal steps for the command

---

dmake/deepobuild.py
test/web/dmake.yml

Closes #259 
Variables are expanded as usual from the `env` related to the service
using the shared volume mount.
`target` validation (must be a full path) is now partially done later
as it must done after variable expansion, which cannot be done during
early yaml validation.

Add variable expansion for SharedVolumeMount `target`

---

dmake/core.py
dmake/deepobuild.py
test/e2e/dmake.yml
tutorial/e2e/dmake.yml

Closes #194 
This is only implemented for Jenkins pipelines for now. This is useful
to protect against tests that never finish (or are abnormally slow).
Details:
- the timeout block is only applied around the `commands` execution:
it excludes dependencies starting, volumes creation, GPU lock
aquisition...
- on timeout, the whole pipeline is aborted, and the GPU lock is
automatically released.

Add `timeout` to services `tests`

---

dmake/common.py
dmake/core.py

Closes #254 
- try to get remote name from upstream branch
- else try with `origin` (for branches with no upstream configured,
but the repository has an existing remote)
- then try to get the remote url
Silently fallback to None or empty string for missing information:
it's not an error to have no remote or a remote named something else
than `origin`.

Allow git repositories with no remote

---

dmake/deepobuild.py
test/e2e/dmake.yml
tutorial/e2e/dmake.yml

Closes #271 
This is only used by the parent service when constructing its runtime
environment.
Thus, it does not change how the needed service should be started,
thus we don't need to distinguish it from other instances of
NeededService to build the global commands DAG: just changed `__str__`
and `__repr__`, not `__ne__` nor `__hash__`.

Add `env_exports` to `needed_services`

---

dmake/deepobuild.py

Fix #274 when dmake is executed without `-d`

Don't emit env_exports without `-d`

---

dmake/core.py

By default jenkins truncates the output on junit tests reports, which
is great for disk space but bad for debugging.

Jenkins: junit: keep long output.

---

dmake/deepobuild.py

Before:
```
ERROR in file engine/api/dmake.yml:
Field source must be a host path or start with 's3://'
```
After:
```
ERROR in file engine/api/dmake.yml:                                                                                                                                                                                                          
Invalid data volume mount: Field `source` '' (expanded from '${MINIKUBE_HOME}') must be a host path or start with 's3://'
```

Better data_volume error message

---

dmake/serializer.py
requirements.txt

* Fix yaml array detection by bumping ruamel.yaml
They now inherit again from `dict` and `list`.
This commit reverts back cb4e58b to
simple, proper type detection.
* Check for dict type when validating YAML2PipelineSerializer
This avoids accidentally matching strings that contain as substring
the name of an expected field.
Example:
```
$ cat dmake.yml
dmake_version: 0.1
app_name: test-repro
build: "string instead of object, containing the string 'commands' which' is an expected object key"
docker:
root_image:
name: ubuntu
tag: 18.04
services: []
```

Fix yaml dict list type check

---

README.md
dmake/core.py
dmake/deepobuild.py
dmake/utils/dmake_run_docker
test/gpu/deploy/Dockerfile
test/gpu/deploy/test-nvidia-smi.sh
test/gpu/dmake.yml

* Support multi GPUs on jenkins
Depends on lockable resources defined on Jenkins: one per GPU:
- name: GPU_0, label: GPUS
- name: GPU_1, label: GPUS
On local mode, give access to all GPUs, as before. Can now also be
overwritten using `DMAKE_GPU=x` environment variable.
* Add NVIDIA_VISIBLE_DEVICES=none when no GPU available
* Add test for GPUs
* Add README for GPUs

Support multi GPU nodes when resource locking GPU in jenkins

---

requirements.txt

There was a bug in upstream ruamel.yaml lib, fixed in 0.15.71.
See https://bitbucket.org/ruamel/yaml/issues/241/insufficient-indentation-with

Fix yaml dump error on kubernetes with user configmap from files

---

dmake/core.py
dmake/utils/dmake_check_tmp_dir

Closes #286 
Jenkins (notably the blue ocean interface) proposes everywhere to
rerun the job. Alas it is *not* supported by DMake, because rerun
masks dynamically generated Jenkinsfiles which depend on dynamically
generated temporary directories, which are cleaned at the end of the
first run => rerun always fail, after some steps, with unhelpful
errors.
Now we start the pipeline by checking that the tmp dir exists, and
print a useful error message if not.

Explain that Jenkins jobs rerun are not supported when it probably happened

---

dmake/deepobuild.py
dmake/kubernetes.py

Closes #291 
Accept absolute path with variable substitution.
It differs from kubernetes.config_maps which accepts path relative to
the dmake.yml file, without variable substitution.
Example:
```yaml
env:
default:
source: ${CONFIG_DIR}/dev.sh
variables:
SECRETS_PATH: ${SECRETS_PATH}
....
kubernetes:
secrets:
- name: my-secret
generic:
from_files:
- key: ssh-privatekey
path: ${CONFIG_DIR}/${SECRETS_PATH}/ssh/id_rsa
- key: ssh-publickey
path: ${CONFIG_DIR}/${SECRETS_PATH}/ssh/id_rsa.pub
```
Also fixed typo: kuberentes -> kubernetes

Add kubernetes.secrets deployment: create generic secrets from files

---

dmake/deepobuild.py
test/web/dmake.yml
test/worker/deploy/start.sh
test/worker/dmake.yml

Closes #159 
Before that we could only define environment variables for all the
services in the dmake.yml file via the root `.env`.
Each service now uses env from root `.env` completed by service
`config.env_override`.
In case of `needed_services[].env`, the started service now uses env
from root `.env` completed by service `config.env_override` completed
by needed_service `.env`.
Each env layer has its values evaluated from the previous layers
resulting env.
Variables in the yaml at the service level are evaluated from the
fully resolved env for the service (root `.env` + service
`config.env_override`).

Add `env_override` in `services[].config`: extra env per service

---

dmake/utils/dmake_deploy_kubernetes

Their `date` doesn't support `--iso-8601`.

Fix dmake_deploy_kubernetes for MacOS

---

README.md
dmake/common.py
dmake/core.py
dmake/dmake

Closes #171
Add dmake command to just build services docker images.
Examples:
- `dmake build worker`
- `dmake build '*'`

Add `dmake build` command

---

Jenkinsfile
dmake/templates/jenkins/Jenkinsfile

Closes #294
Useful when debugging to check container state, logs, content before
DMake cleanup.

Expose DMAKE_PAUSE_ON_ERROR_BEFORE_CLEANUP on jenkins builds

---

README.md
dmake/commands/release.py

- Semver tags were not well sorted (only by minor version for some reason) and this was causing troubles for the next part of the code which was depending on this.
`semver.VersionInfo` already support comparison operators. 
- Fixed question message which was not clear
- Updated readme

Fixed version sorting in dmake release command

---

dmake/docker_config.py

(it happens when using GCP Container Registry)
`credentials_store` variable was wrongly set by the for loop...

Fix docker_config when alternate credHelpers exist

---

dmake/docker_config.py
dmake/docker_registry.py

`index.docker.io` was the original URL (registry v1). Since v2 the
official registry URL is `registry-1.docker.io`:
https://github.com/moby/moby/blob/a3f626d1019bd049dcc46ac8f64fe08b057e89f9/registry/config.go#L49-L52
And for retro-compatibility the client config.json file auth section
still uses `https://index.docker.io/v1/` as key.
Also raise a more complete exception when the registry returns 404.

Use official registry URL

---

dmake/docker_registry.py

It is not strictly correct as the authenticated session has an
expiration date (on the official docker hub it is valid for 600s).
In such case the `TokenExpiredError` is raised.
We assume it won't happen: dmake execution should be much faster than
that. If it breaks in practice, we will have to implement our own
cache which checks the expiration date.
Test on dmake itself:
- before: 3.953s
- after:  3.088s

Add cache for getting docker registry authenticated session

---

dmake/templates/jenkins/Jenkinsfile

dmake is faster with python3 (we have caching on docker registry
calls).

Use python3 on Jenkins

---

dmake/deepobuild.py
test/e2e/.dockerignore
test/e2e/.gitignore
test/e2e/dmake.yml

Related to #311 v0.
For now dmake doesn't really support building artifacts (such as pip
packages), but we can use `dmake test` with a mounted volume to build
artifacts and pass them to the host.
This commit simplifies this by allowing host paths relative to the
dmake.yml file for `tests.data_volumes`.

Allow relative host path in data_volumes for artifact creation during dmake test.

---

dmake/templates/docker-base/install_pip.sh
dmake/templates/docker-base/install_pip3.sh

This avoids accidentally using newer pip with breaking changes.
Latest one: new pip 19:
```
no such option: --process-dependency-links
```
Using pip 9.0 branch as it's the one shipped in ubuntu:18.04 and it
has no major breaking change compared to previous versions.

Freeze pip version to 9.0.3 when using deprecated python{,3}_requirements

---

dmake/utils/dmake_deploy_kubernetes

Closes #130.
Reverts #129 now that a fix was released upstream (kubectl 1.7.14, 1.8.0).
Also annotate all resources on k8s deployment, not just the SERVICE Deployment.

Add back dmake annotations on deployed resources

---

dmake/core.py

Previously it always returned `0`.
Now it forwards the generated bash script return code.
`dmake` can now more reliably be used for scripting.

dmake now returns a meaningful return code in case of error

---

Jenkinsfile
README.md
dmake/commands/__init__.py
dmake/commands/deploy.py
dmake/common.py
dmake/core.py
dmake/deepobuild.py
dmake/dmake
dmake/templates/jenkins/Jenkinsfile

Closes #211, prerequisite for #235.
* Support cli options --no-dependencies, --standalone, -s
* Now default to `--dependencies` for dmake shell, run, test, deploy
It will avoid accidentally using remote resources (such as remote
database): use `--standalone` or `-s` to force disabling local
dependencies execution.
Also, now, `dmake deploy` can be executed without dependencie
* Update the README with the breaking change around `--dependencies`
* Update the Jenkinsfiles to use new --dependencies & --standalone

Default to --dependencies & add cli options --no-dependencies, --standalone, -s

---

dmake/core.py

Previously it accidentally worked in some cases, and broke in
others (notably with `DMAKE_SKIP_TESTS=1`).
This is the same workaround as for `dmake test` (see #245), with the
same limits:
- when deploying a service instead of all (`*`), we now also deploy its
dependencies services. To avoid deploying (and testing) the
dependencies, use the new `--standalone` (or `-s`) flag.
Also, generalize activate_needed_services: accept any command.

Force deployment order using service runtime dependencies

---

dmake/common.py

This avoids infinite loop when recursing on error.
Also disambiguate between rev and filename.

Properly handle errors in git get upstream remote

---

dmake/core.py

The `test` stage executes containers (except for the shell which is in
`deploy`): let's call it `Running App` instead of `Testing App` which
implies there are tests.

Better stage name in execution plan

---

dmake/dmake

It could lead to accidents, but so does bypassing that by manipulating
local git branch names.

Allow changing branch for `dmake deploy`

---

dmake/core.py

It was accidentally broken by #346.

Fix Jenkins GPU resource reservation

---

install.sh

* Unconditionally install dmake/config.sh to all *srch
Fixes #361: re-installing dmake after having added a new
shell (e.g. zsh) previously skipped the dmake/config.sh setup
in *shrc.
* Semi support dmake completion in zsh
It doesn't seem to work perfectly though...
* Remove deprecated dmake config file migration

Better zsh support (~bash completion, install.sh to .zshrc)

---

install.sh

Related to #118; it simplifies `install.sh` while still keeping the
feature for now if really needed (simply manually export
`DMAKE_SSH_KEY`).

Start deprecating DMAKE_SSH_KEY for new setups

---

dmake/common.py
dmake/core.py
dmake/deepobuild.py
dmake/docker_image.py
dmake/python_2x.py
dmake/python_3x.py
dmake/serializer.py
docs/EXAMPLE.md
docs/FORMAT.md
test/e2e/dmake.yml
test/worker/dmake.yml
tutorial/worker/dmake.yml

One may want to use external images in a project, e.g. the pre-built Deepomatic neural worker version.
You may be tempted to use dmake links to define this service, the problem is that you need to link it to RabbitMQ to communicate with it, and there is no way to do that with dmake links.
So you end up using a service (that you can link to a link), but there is no way to use an external image for a service, you have to build a Docker image. So this PR allows to do it.

Allow to define services that use external images

---

dmake/core.py

Closes #353
Since (#344 and) #338 we re-use the `needed_services` dependency tree
to order the deployments steps.
This had an unexpected consequence: "duplicated" services via
customization via `needed_services` also duplicated their deployment.
Customized needed_services make in fact only sense for local execution
as a dependency during `dmake shell/test/run`: it should *not* create
new deployments.
PR #334 + #338 changed the semantic of `dmake deploy`: deployment is
now recursive. We still want that.
This commit resolves all this by following on #338:
- recurse at the deployment level
- but strip service customization in recursion

Avoid duplicate deployments for customized needed_services

---

dmake/utils/dmake_run_docker

This is a test to use [telepresence](https://www.telepresence.io) for a more integrated `dmake shell` experience: local container execution in the full network context of the remote kubernetes deployment.
```
DMAKE_TELEPRESENCE=1 dmake shell -s foo
DMAKE_TELEPRESENCE=1 DMAKE_TELEPRESENCE_ARGS=--mount=false dmake shell -s foo
```
- only for dmake shell
- select correct kubernetes context according to deployment declared in dmake
- support `--swap-deployment` according to some config in dmake.yml

Optionally use telepresence for dmake shell

---

dmake/common.py
dmake/deepobuild.py
dmake/dmake

Closes #317.
Sometimes we want persistence with `dmake run`, and sometimes we
don't (running multiple instances of the application at the same time
would break things with persistence by host mount).
Keep the default of non persistence for `dmake run`.
Only add the option to `dmake run` for now.
- `dmake shell` remains always persistent
- `dmake test` remains never persistent
- Shared volumes remains never persistent

Add --[no-]docker-links-volumes-persistence option to dmake run

---

dmake/deepobuild.py

Closes #397 
We need to access `/dev` with `--privileged` on Jenkins for hardware support.
Unfortunately dmake removed `--privileged` from `docker_opts` when the build was not local.
It was not really useful a protection: just remove it.

Remove docker_opt is_public clean

---

dmake/deepobuild.py

Previously we did it for dmake shell so there is no issue related to
DMAKE_UID, but in fact we also need it for dmake run/test: sometimes
the containers have non root users and must be able to write to the
shared volume anyway.
Furthermore, the kubernetes equivalent (emptyDir) does that too.

Always chmod 777 the shared volumes

---

dmake/commands/stop.py
dmake/common.py
dmake/core.py
dmake/deepobuild.py
dmake/docker_image.py
dmake/test_common.py
dmake/utils/dmake_run_docker
dmake/utils/dmake_run_docker_link

Closes #23, dmake should finally support dependabot.
- Add docker mode for sanitation, and add a unique variant
- Factorize docker image name prefix in a new global: name_prefix
- Sanitize the default docker image tag name: git branches can contain invalid characters
- Support git branches with slashes

Support extra characters in branch name

---

dmake/common.py
dmake/docker_image.py
test/e2e/dmake.yml
tutorial/e2e/dmake.yml

It allows applications to reconstruct dmake built docker images tags
more easily (notably since #407).

Add IMAGE_TAG_PREFIX host environment variable

---

dmake/core.py

close #405 
```
Commands have been written to /tmp/dmake_tmp_1569951000375351679_17527/DMakefile
Careful ! Are you sure you want to deploy ? [y/N]  y
```
or 
```
Commands have been written to /tmp/dmake_tmp_1569951200428491684_10785/DMakefile
Careful ! Are you sure you want to deploy ? [y/N]  
Aborting
```

Default prompt choice for a deploy command will be no

---

.gitignore
Jenkinsfile
dmake/cli.py
dmake/common.py
dmake/core.py
dmake/deepobuild.py
dmake/dmake
setup.cfg
test/Makefile
test/e2e/dmake.yml
test/test-resources/graph.build.test-web.gv
test/test-resources/graph.deploy.*.gv
test/test-resources/graph.deploy.test-e2e.gv
test/test-resources/graph.deploy.test-k8s.gv
test/test-resources/graph.run.test-e2e.gv
test/test-resources/graph.run.test-web2.gv
test/test-resources/graph.shell.test-web.gv
test/test-resources/graph.test.*.gv
test/test-resources/graph.test.test-e2e.gv
test/test-resources/graph.test.test-web2.gv
test/test_graph.py
test/web/dmake.yml

Test several dmake commands, and compare expected internal graph (via
the `--debug-graph` feature).
DMake generates an internal graph planning the various steps to
execute, according to the command-line and the dmake.yml files.
Example:
service foo with needed_service bar, `dmake test foo` execution plan
graph would have the following edges:
- test foo -> build foo
- test foo -> run bar
- build foo -> build-base foo
- run bar -> test bar
- run bar -> build bar
- test bar -> build bar
- build bar -> build-base bar
This graph can be explored with `dmake --debug-graph` options.
To make execution plan construction easier when adding features to
DMake, this PR adds tests comparing expected with actual execution
plan graph dumps.
The reference graphs can be generated with:
```
make -C test …
```

Add DMake internal plan graph tests

---

dmake/cli.py
dmake/common.py
dmake/core.py
dmake/docker_image.py
test/.dockerignore
test/test-resources/graph.deploy.*.gv
test/test-resources/graph.test.*.gv
test/worker/Dockerfile
test/worker/deploy/start.sh
test/worker/dmake.yml

MVP for #425
- Auto detect changed directories and services with `+` as service name
Also, work locally with default CHANGE_TARGET=@{upstream}.
- Change detection: only use origin/ in non-local mode
This allows easy CHANGE_TARGET override locally:
- CHANGE_TARGET=HEAD dmake test +
- CHANGE_TARGET=master dmake test +
- CHANGE_TARGET='' dmake deploy +  # uses deployed_version_{branch}
tag as in jenkins
- Support build.context: ../ with `+` change detection: manually declare additional contexts
Add `service.config.docker_image.source_directories_additional_contexts list
- extended build/source context: only activate concerned service, not the whole dmake.yml
- For jenkins non-PR builds change detection we need to fetch tags
- Cleanup branch/change detection
ghprb* env vars were unused …

Auto detect changed directories and services with '+' as service name

---

dmake/core.py
dmake/deepobuild.py
test/test-resources/graph.deploy.*.gv
test/test-resources/graph.deploy.test-e2e.gv
test/test-resources/graph.test.*.gv
test/test-resources/graph.test.test-e2e.gv
test/test-resources/graph.test.test-web2.gv
test/web/dmake.yml

related on #223
Fine-grained control of needed_services usage: for parent run, for parent test.
Later: For fully independent unit-tests we would need to also control
needed_links; possibly by merging needed_links into needed_services.
In the meantime it's fine as needed_links do not recursively depend on
anything.
When working on a specific service (or on services found via change
detection), the `test` step previously always started (recursively)
the needed_services (and also started the links services): dmake
assumed they were integration tests.
Now we can individually disable starting each needed_services: for
run, and test.
Example:
```yaml
services:
- service_name: foo
needed_services:
- service_name: bar
needed_for:
run: true   # foo needs bar to run
test: true  # foo needs bar to …
```

Allow faster unit-tests without dependencies at test-time

---

dmake/common.py
dmake/core.py
dmake/deepobuild.py

MVP for #424
When in change detection mode, we work on all changed services, and test their parent recursively.
Doesn't change anything for other steps than `test`. Notable `dmake deploy +` will still only deploy changed services, not its tested parents.
Can be overridden with `needed_services[].needed_for.trigger_test` boolean.

Change detection mode: test parent dependencies

---

dmake/deepobuild.py
dmake/serializer.py
test/e2e/dmake.yml
test/gpu/dmake.yml
test/k8s/dmake.yml
test/web/dmake.yml
tutorial/e2e/dmake.yml

related to #432
warning for #432 example:
```
[DEPRECATION WARNING] D002: Field 'env:default:variables' in 'dmake.yml' should contain a string, it currently contains a <class 'bool'>: True. Add quotes arount the value.
[DEPRECATION WARNING] D002: Field 'docker:root_image:tag' in 'dmake.yml' should contain a string, it currently contains a <class 'float'>: 18.04. Add quotes arount the value.
[DEPRECATION WARNING] D004: Field 'services:config:ports:container_port' in 'dmake.yml' should contain an int, it currently contains a bool: True.
```

Better yaml values usage: warn about unexpected use-cases

---

dmake/utils/dmake_run_docker

At that point in execution it's an environment variable, not a bash
variable that can store an array.
=> Usage: DMAKE_TELEPRESENCE_ARGS="--foo --bar"

Fix DMAKE_TELEPRESENCE_ARGS env var

---

dmake/utils/dmake_build_docker

`docker build --progress=plain` with buildkit displays the full build output for each step, and also dockerignore debug logs

DMAKE_DEBUG=1: docker build --progress=plain for buildkit

---

dmake/core.py

Implements v1 for #445 
- dmake now depends on `code-coverage-api` Jenkins plugin
- calculate diff for PRs
- for now: just one merged report; could be rendered configurable from dmake.yml
- for now: keep the old coberturaPublisher
- for now: do not publish source code because paths are not relative to the correct directory (inside containers, outside containers, relative to report path?)

Use newer publishCoverage for jenkins code coverage

---

dmake/deepobuild.py
dmake/templates/docker-base-raw-root-image/make_base.sh
test/web/dmake.yml
test/worker/deploy/dependencies.sh
test/worker/dmake.yml
tutorial/web/deploy/dependencies.sh
tutorial/web/dmake.yml
tutorial/worker/deploy/dependencies.sh
tutorial/worker/dmake.yml

closes #93 
related to #118
Only use user install_scripts to build the base image from the root:
deprecate old way where dmake added many things by itself to the root
image (and assumed it was debian-based), to support deprecated features:
- dmake-managed python requirements (raise error when used with raw_root_image)
- ssh agent/key in the build container
It allow using non debian-based root images (just requires bash, which
could be relaxed too).
It should be faster to build too: less apt install commands.
Main change: need to install 'ca-certificates' apt package manually.

Simplify base image building: raw root image 

---

dmake/core.py
test/web/dmake.yml

Support test `html_report.directory` ending with `/` on jenkins
Previously it failed in `docker cp`:
```
invalid output path: directory
"/repo/.dmake/tests_results/xxx/app/service/cover"
does not exist
```
=> `docker cp` is not perfectly specified with trailing slashes, but
it seems to work as expected when removing it.
Tested with docker 19.03.3.

Test non-regression trailing slash in html_report dir copy

---

Jenkinsfile
dmake/templates/jenkins/Jenkinsfile

MVP for #415
It works by just planning/generating the deployment step (in practice
also the build step as it's not skippable...): all files are read,
template instantiated, and somewhat validated by kubectl dry-run.
It thus catches:
- missing referenced files
- wrong templates (undefined variable)
- some wrong k8s manifest: unknown fields, etc, but not all
issues (e.g. env[].value yaml type is *not* checked to be a string)
- it does check some schema validation via remote api definition (properly since #358)
It also supports no deployment (i.e. no `deploy` section (which is different than empty `deploy` array, which asks dmake to push docker images), now required when images are local only (no `foobar/` prefix)).
This will still test the k8s deploy dry-run with `DMAKE_SKIP_TESTS=1`, which …

Test kubernetes deployment manifest templates in PRs

---

install.sh

Previously it would append the `source $HOME/.dmake/config.sh` string in the last line if no trailing newline, breaking both lines intent.

install.sh: support .{bash,zsh}rc with no trailing newline

---

dmake/docker_image.py

Close #444 
It was never used, it's not usable: use static versions instead.

Stop pushing :latest docker image alias

---

dmake/commands/release.py
requirements.txt
test/test_release_command.py

Close #462 (fix prerelease bumping)
- **Order** The check ensure the new version is strictly superior to the previous version.
- **Main parts** The check still ensure no version is skipped when bumping the major/minor/patch part or finalizing (=removing extensions, i.e. prerelease and build parts).
- **Prerelease** The releaser has now more flexibility on the pre-releases: they are not checked too much because they can vary a lot. For instance token can change between version (`alpha` -> `beta`) or between projects (`rc`, `dev`...) (https://semver.org/#spec-item-9). Only the alphabetical order is checked if all the other parts are identical
- **Build** If only the build part differs, there is no precedence (https://semver.org/#spec-item-10) and the bump is invalid (arbitrary choice, can …

Release command: fix prerelease bumping

---

dmake/commands/release.py

They are set to empty string by the install.sh script...
Closes #459

Raise error on empty DMAKE_GITHUB_TOKEN/DMAKE_GITHUB_OWNER env vars

---

dmake/deepobuild.py
test/k8s/dmake.yml

It was effectively not working because of per-stage pruning.
Closes #450.

Reject multiple kubernetes deployments on same dmake service, k8s context and namespace

---

dmake/common.py
dmake/deepobuild.py
dmake/kubernetes.py
dmake/utils/dmake_deploy_kubernetes

Before, when running dmake deploy locally, the image name didn't change, so the deployment spec.template usually didn't change (it did change when env var values changed), resulting in new code not deployed until pod deletion.
(in any case this still needs a `imagePullPolicy: Always` for these dev envs so k8s re-downloads the (new) docker image.
Now, set dmake annotations notably with timestamp (so it's unique) not only in metadata  but also in spec.template.metadata when spec.template exists; forcing a new deployment.
Also removed annotations set by dmake_deploy_kubernetes at runtime: it's all done at generation time now.
Later we could also set the kubernetes.io/change-cause this way (but maybe add it only at the top-level? maybe only for app/v1?).

Add k8s annotations, also in spec.template.metadata to force redeploy with the deploy timestamp

---

dmake/cli.py
dmake/commands/__init__.py
dmake/commands/graph.py
dmake/common.py
dmake/core.py

Useful for dmake users to discover/understand the services dependencies graph.
The `dot` program is required to generate the graph; graphviz will throw an intelligible exception if it's missing.
Example with dmake own tutorial/test graph:
```
$ dmake graph --help
usage: dmake graph [-h] [--output OUTPUT] [--format FORMAT]
optional arguments:
-h, --help       show this help message and exit
--output OUTPUT  The generated DOT graph filename.
--format FORMAT  The generated DOT graph format (`png`, `svg`, `pdf`, ...).
$ dmake graph
...
Generated graph in files 'dmake-services.gv' and 'dmake-services.gv.png'. You can open the first with `xdot` for example.
```

Add dmake graph for services dependency graph generation

---

dmake/deepobuild.py

Closes #455 
It was in fact not needed for a long time: k8s completion wait is done
via dmake-injected labels, not Deployment name.

Remove ${SERVICE_NAME} in kubernetes yaml templates

---

dmake/core.py

Some `echo` are displayed in step views, some not, no idea why. it seems the ones talking about `::shared_volume` are shown, others not, no idea why:
May or may not be related to https://issues.jenkins.io/browse/JENKINS-53649
Implemented workaround from https://stackoverflow.com/a/58558537

Workaround scripted pipeline 'echo' not always showing up in high-level interfaces

---

dmake/common.py
dmake/core.py

related to #424
Issue:
- Child1 test triggered by source change
- Parent test triggered by child source change (technically, when activating Child1 service for command==test)
- Parent test needs Child1 and Child2 run
- Child2 run needs Child2 test <-- issue here: we should not test Child2; but we should keep the "`Child2 run`->`Child2 test`" dependency if for another reason `Child2 test` is created (e.g. Child2 sources have also changed, or Child2 test is triggered by one of its own children source changed (recursively))
On change detection mode, only create the dependency from run node to
test node if test node already activated otherwise. Previously it
always created the test node in addition to linking run to test to
guarantee execution order.
That previous test node creation …

Change detection trigger test v2: bugfix for non-trivial cases: Don't cascade back from the triggered parents on siblings

---

dmake/utils/dmake_deploy_kubernetes

This colorizes kubectl outputs, much useful to read verbose dmake deploy output.
Using https://github.com/dty1er/kubecolor
Limit: `kubectl apply` is not yet colored, cf https://github.com/dty1er/kubecolor/issues/37

Kubernetes deployment: use kubecolor if available

---

dmake/cli.py

Regression introduced by c37cd68055cf2b54e658067c0e87f9cb182c5d40,
which bumped argcompletion, which included an undocumented breaking
change (https://github.com/kislyuk/argcomplete/pull/246) that lead to
generating `d m a k e` instead of `dmake` in the final bash script,
breaking the completion (and maybe other things).
How to update (run from a directory containing a dmake project to avoid `Current directory is not a Git repository` error):
```
rm  "${DMAKE_CONFIG_DIR:-$HOME/.dmake}/completion.bash.inc"  
dmake completion > "${DMAKE_CONFIG_DIR:-$HOME/.dmake}/completion.bash.inc" 
source "${DMAKE_CONFIG_DIR:-$HOME/.dmake}/completion.bash.inc" 
```
(see `dmake completion --help` for other shells than bash)

Fix argcompletion shell code generation

---

dmake/templates/docker-base/install_pip.sh
dmake/templates/docker-base/install_pip3.sh

Later: just drop these features
See https://github.com/pypa/get-pip/issues/29 for more context.

Pin bootstrap.pypa.io pip installer for specific python versions, the default one now requires python 3.6+

---

dmake/commands/release.py
dmake/deepobuild.py
dmake/kubernetes.py

- lazy import some large and uncommon modules
- don't use both yaml and ruamel.yaml: normalize on the later via dmake.common
How to benchmark:
```
$ time _ARGCOMPLETE_SUPPRESS_SPACE=1 COMP_LINE='dmake shell ' COMP_POINT=12 COMP_TYPE=63 _ARGCOMPLETE=0 dmake 
$ time python3 -c 'import dmake.cli'
$ time python3 -X importtime -c 'import dmake.cli' |& sort -k5g
```

Faster dmake auto-completion via faster imports (lazy): 270ms->110ms

---

dmake/deepobuild.py

1df5824fb7b0a044e1cb894d17ab866a33b55762 / #477 fixed the scripts
behind `python_requirements` (and `python3_requirements`), which were
deprecated a long long time ago (see #77).
Sadly, in doing so, the md5 of the base image source changed, because
these scripts were always added to the base image, even when unused.
This resulted in user visible issue: invalidation of all base images,
for nothing, since this feature is (almost) not used.
The end-goal is to remove that altogether, but in the meantime we can
avoid a double base image hash change by anticipating that end-goal,
while still keeping the feature working for now: don't emit these
files when they are not needed.

Don't invalidate base image build cache when fixing largely unused `python_requirements`

---

install.sh

It usually doesn't change, but updating argcomplete may change it, and
there was previously nothing to handle that case.
And it's cheap to regenerate!

Always reinstall the shell completion in dmake install.sh, in case it changed

---

dmake/utils/dmake_test_get_results

running locally tests 2 times results in unexpected result:
docker cp mycontainer:/app/cover/ cover/
cover/ is ok
second run:
docker cp mycontainer:/app/cover/ cover/
cover/cover/ is created, it should not exist
(it happens with `dmake test \*` on dmake repo for `test/web/cover/`)
For files and not directory it already worked OK because nesting is
not possible.
solution: docker cp on parent path is idempotent.
On jenkins we always create a unique temporary directory, so there is
never a 'second run' on an existing target directory: that's why we
never saw any issue on test results collection on jenkins.

Fix dmake_test_get_results on non-empty target dir, i.e. on local machine

---

Jenkinsfile
dmake/cli.py
dmake/commands/graph.py
dmake/common.py
dmake/core.py
dmake/deepobuild.py
test/test-resources/graph.build.test-web.gv
test/test-resources/graph.deploy.*.gv
test/test-resources/graph.deploy.test-e2e.gv
test/test-resources/graph.deploy.test-k8s.gv
test/test-resources/graph.run.test-e2e.gv
test/test-resources/graph.run.test-web2.gv
test/test-resources/graph.shell.test-web.gv
test/test-resources/graph.test.*.gv
test/test-resources/graph.test.test-e2e.gv
test/test-resources/graph.test.test-web2.gv
test/test_graph.py

This MVP only works on Jenkins, where we have higher-level primitives, and more resources control.
Enable it via `DMAKE_PARALLEL_EXECUTION = 1` environment variable.
test:`dmake test \*`, with base image and image already in cache, a.k.a. worst case for easy parallel gains (docker builds are all parallelizable)
Full command when debugging this:
```
DMAKE_PARALLEL_EXECUTION=1 CHANGE_BRANCH=master DMAKE_ON_BUILD_SERVER=1 dmake --debug-graph-and-exit --debug-graph-pretty --debug-graph-group-by height deploy \*
```
- `DMAKE_PARALLEL_EXECUTION=1` to enable parallel execution
- `CHANGE_BRANCH=master` to fake Jenkins environment (i.e. a PR to be merged into `master` branch), so it generates with Jenkinsfile instead of bash format (which would fail as parallel is not supported there)
- …

Parallel Execution on Jenkins

---

Jenkinsfile
dmake/common.py
dmake/core.py
dmake/deepobuild.py
dmake/utils/dmake_run_docker_test
test/web/dmake.yml

closes #374
Tricky case: when tests failed, some tests may have not been executed,
so tests results files may be missing.
We still want to collect them if possible, without raising extra error
if we cant.
We still want to fail when the collection failed when the tests
succeeded though.
Current solution: duplicate the tests results collections commands,
wrap tests, and individual collections, with try/catch/rethrow and
help messages.
On bash, use https://stackoverflow.com/a/25180186/15151442 for
try/catch.
Maybe a better way to handle that would be to have a "super cmd" that
takes the individual test results collections cmds, and handle the
error handling and duplication in generate_command_bash|pipeline()?
Also:
- always store container id in txt files, even if tests failed
- always …

Collect tests results even when some tests fail (or timeout) 

---

dmake/deepobuild.py
test/.dockerignore
test/web/dmake.yml
test/worker/.dockerignore
test/worker/dmake.yml

Useful to force disable host_port when a service is used as a
dependency, and still keep this available when that service is
directly started; for example a frontend, also started as a dependency
of the backend, to support front, back, and both-together development
modes.
Add useless host_port and use_host_ports usage in test/*/dmake.yml to
cover that part.
This doesn't properly cover all edge cases regarding NeededService
specialization: we assume all instances for a service that are
otherwise identical are using the same value for
`use_host_ports`. It's undefined behavior to not do that.
Also improve test/*/.dockerignore for faster tests.

Add needed_services[].use_host_ports

---

Jenkinsfile
dmake/templates/jenkins/Jenkinsfile

Closes https://github.com/Deepomatic/squad-infra-deploy/issues/9
The implementation uses `milestone()` in that way: https://issues.jenkins.io/browse/JENKINS-43353?focusedCommentId=395851&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-395851
It can be deactivated by setting `DEFAULT_ABORT_OLD_BUILDS_ON_PR=false` on your Jenkinsfile before `load "${DMAKE_JENKINS_FILE}"`.
What it does:
when that option is enabled (by default), on jobs for PRs, it'll abort all previous builds that are still running, at the beginning of the current build execution, before it reserves a jenkins executor (so it works even when the executors are all busy and the new build would otherwise be in queue) (see [flyweight executors](https://support.cloudbees.com/hc/en-us/articles/360012808 …

Abort old builds on PR jobs

---

dmake/core.py

Fix regression introduced by 2d00408a8274ea3bc63d2a9de6142fc4481afe41
Bash doesn't like:
```
echo -e '
{
}
```
=> DMakefile: line 56: syntax error near unexpected token `}'
Solution: guarantee at lest one command is in the block: the stage name echo
```
{ echo -e '
}
```

Fix bash invalid syntax error on empty stage

---

dmake/core.py

CoberturaPublisher is done at the end of the execution because it
cannot be duplicated (at least it was the case several years ago when
it was plugged-in).
With 1f3c17db399c85e923e5506e1c3d33636473bb57 / #482 we tried to
eagerly collect tests results even when tests failed, but didn't
properly handle that late collection in the case of errors before any
test step: the tests results won't exist.
Because it's a global, late collection, we cannot do the fancy double
collection with/without error propagation that we did in #482 for the
other tests results collections.
That's OK; the situation is explained to the user.

Fix cobertura_report collection error because of earlier error, before tests

---

dmake/cli.py
dmake/core.py
docs/USAGE.md

- remove the possibility to skip cleanup: just keep dmake alive while
error is investigated, then press enter to finish with cleanup
- add multiple suggestions on how to investigate the error
- better dmake run messages, with link to dmake stop

Better message when an error occurred

---

dmake/core.py

See https://jenkins.io/redirect/groovy-string-interpolation
- before it was groovy that injected the git password as string to the
sh commandline
- now the git password is passed as env var, and it's sh that string
interpolates
Later we could even use something like https://stackoverflow.com/questions/8536732/can-i-hold-git-credentials-in-environment-variables

Fix insecure string interpolation when dmake pushes git tag after a deployment on jenkins

---

Jenkinsfile
README.md
dmake/common.py
dmake/core.py
dmake/deepobuild.py
dmake/kubernetes.py
dmake/utils/dmake_deploy_kubernetes
test/k8s/dmake.yml

- Fix jenkins PR kubernetes manifests validation
- Switch to kubectl 1.18+ --dry-run=server when verifying generated kubernetes manifests
- DMAKE_LOGLEVEL env var to configure dmake log level
- git rev-parse doesn't read `--` as expected: remove it

Various fix

---

CONTRIBUTING.md
Jenkinsfile
test/k8s/dmake.yml

- use a new `DMAKE_TEST_K8S_CONTEXT` environment variable
- set it to minikube in Jenkinsfile for dmake own tests where we
already used minikube
- added a CONTRIBUTING doc to explain this setup to test (part of) the
kubernetes deployment

Stop hardcoding `main` kubernetes context in dmake tests

---

dmake/templates/jenkins/Jenkinsfile

Abort old builds on Jenkins jobs for some branches.
This follows up on #485.
What it does:
- Abort all previous builds for branches present in the comma separated list defined by `DEFAULT_ABORT_OLD_BUILDS_ON_BRANCHES`.
- It can be deactivated if the `DEFAULT_ABORT_OLD_BUILDS_ON_BRANCHES` list is empty (the default).

Abort old builds for some branches

---

dmake/cli.py
dmake/commands/release.py
docs/USAGE.md

also, don't quiet when git fetch tags: it hides errors.
TODO later: use https://docs.github.com/en/rest/reference/releases#generate-release-notes-content-for-a-release , with controllable previous_tag_name (it's not exposed from web ui)

dmake release: cleanup messages, create draft release

---

dmake/common.py
dmake/deepobuild.py

closes #520
When deploying on virtual-git-branches-as-dmake-environments, we select the env with `--branch`.
This previously resulted in the `dmake.deepomatic.com/git-branch` annotation containing the environment name instead of the real underlying git branch name, which is more informative of what code is really deployed.
We now generate both values, as well as print them in the header logs
when they are different.

kubernetes annotations: set both real git branch and dmake environment branch name

---

dmake/utils/dmake_deploy_kubernetes

closes #527
kubernetes Deployments with `dmake.deepomatic.com/wait: 'false'` labels are not waited for.
Remarks:
- all other values, or missing key, are interpreted as `true`: dmake waits for them after the `kubectl apply`, as before
- all deployed kubernetes resources are still resumed at the end of the deployment with the `kubectl get -f xxx`

Skip waiting for kubernetes Deployments with `dmake.deepomatic.com/wait: 'false'` label

---

dmake/utils/dmake_deploy_kubernetes

closes #529
It uses the `kubectl-argo-rollouts status` command, which may not be available.
If it's not available: warn about it and just run `kubectl get`.
Also supports the recent #528 skip wait (useful for manual promotion)

Support waiting for Argo Rollouts kubernets kinds like we do for native Deployments

---

dmake/templates/jenkins/Jenkinsfile

related to IN-126
When set (from a new Jenkinsfile.<deploy_region>), dmake is called with `--branch=<the_actual_gitbranch>-<deploy_region>`, using the 'environment branch' suffix as a ~deployment profile for different regions.
dmake Jenkinsfile entrypoint previously supported:
- `DEFAULT_DMAKE_*` groovy variables to change the default job parameters values
- `OVERRIDE_DMAKE_*` groovy variables to override parameters (hackish)
This introduces a new kind:
- `dmake_arg_*` groovy variables to pass dmake arguments which are not exposed as job parameters
This is not (yet) supported for Jenkins PR builds as we don't need it, and extra care would need to be taken notably for the kubernetes manifest pre-run test.
This is easy when limited to deployment branch jobs: it's for `env.BRANCH_NAME`.

Add new dmake arg for Jenkinsfile control: dmake_arg_deploy_region

---

dmake/docker_image.py
docs/EXAMPLE.md
docs/FORMAT.md

closes #526
Add special env vars prefixed with `_` just for this tag name specification, so we can easily reproduce the previous behavior: `${_BRANCH_SANITIZED_FOR_DOCKER}-${_BUILD_ID_OR_LATEST}${_VARIANT_SUFFIX}`
=> it's the new default.
=> Actual default generated value doesn't change.

Support docker image tag customization with environment variables

---

dmake/templates/jenkins/Jenkinsfile

For repositories with manual deployments (for more control) via jenkins, we can improve the "build with parameters" UI and UX.
- Comment explaining how to use `DEFAULT_DMAKE_*` and `OVERRIDE_DMAKE_*`
- Add fancy parameters separators: better readability: basic vs advanced DMake parameters
- Improve `DMAKE_APP` doc & error on empty value
- It's now recommended to set `DEFAULT_DMAKE_APP=''` in calling Jenkinsfile to force the end-user to choose a dmake service explicitly.
- `DMAKE_COMMAND` now proposes a static list of choices (relevant to CI/CD) instead of automatic choice or text input.
- The default choice reflects the previous automatic choice: PR vs non-PR.
- We still support that automatic choice with `OVERRIDE_DMAKE_COMMAND` too.
This should be retro-compatible: no functional change …

Better jenkins "build with parameters" UX

---

dmake/templates/jenkins/Jenkinsfile

It's especially useful when projects set DEFAULT_DMAKE_WITH_DEPENDENCIES=false: the problem was hidden with the default default: --dependencies was implicit.
Also make dependencies explicit now.
No other jenkins-supported commands reject the `--dependencies` flag.

Ignore DMAKE_WITH_DEPENDENCIES when it's not relevant: when DMAKE_COMMAND=build

---

dmake/templates/jenkins/Jenkinsfile

Previously the DMAKE_SKIP_TESTS parameter was implicitly passed to the `dmake` process thanks to jenkins exposing all job parameters also as environment variables.
This makes things harder to debug when looking at the actual dmake command.
This is a frequent enough case to improve it.

Explicit DMAKE_SKIP_TESTS=1 in dmake call build logs on jenkins

---

dmake/cli.py
dmake/templates/jenkins/Jenkinsfile

later, tests should be independent of ~deployment environment, but for
now they are not.
- dmake jenkinsfile supports only build, test and deploy commands
- dmake build does not support --branch override: it wouldn't make
sense: builds are independent of environments
now: dmake jenkinsfile ignores dmake_arg_deploy_region if (actual)
dmake command is `build`.

Fix jenkinsfile build with deploy region

---

dmake/docker_registry.py
dmake/test_docker_registry.py

- ubuntu:20.04 is now only available with new 'application/vnd.oci.image.index.v1+json'
- ubuntu:12.04 is only available with old 'application/vnd.docker.distribution.manifest.v2+json' (and should hopefully stay that way in the future, for tests stability)
- asking only the new oci.image.index triggers an implicit fallback to 'application/vnd.docker.distribution.manifest.v1+prettyjws' for old images, with a different digest, we don't want that (we want digest stability for base image cache)
- `Docker-Content-Digest` header is still a valid digest with the new content type
=> ask both content types, priority to new one.
Added a quick unit test testing get_image_digest on both old and new content-types (hopefully it should stay stable on docker hub side; if it changes, we should adapt it). …

Support new OCI image index content type to get docker image digest from registry (content digest)

---

dmake/utils/dmake_deploy_k8s_cd
requirements.txt

Bump kubernetes client version to [22.6.0](
https://github.com/kubernetes-client/python/blob/release-22.0/CHANGELOG.md)
DMAKE_DEBUG=1 is broken: missing kubernetes debug logs after first request, cf https://github.com/kubernetes-client/python/issues/1799

Bump kubernetes client version to 22.x

---

dmake/utils/dmake_run_docker

Sometimes it's useful to add more arguments to the docker run command.
Fo example:
DMAKE_DOCKER_RUN_EXTRA_ARGS=--add-host=host.docker.internal:host-gateway so the containers can talk to a service exposed on the host. (use `docker network inspect bridge | jq -r .[].IPAM.Config[].Gateway` to get the docker IP on host side to not expose to your whole LAN)
Implementation details:
Since bash array vars cannot be passed via env vars, we limit our support (no space inside arguments), and rely on the bash word split on spaces with no variable quoting.
volontarily non-escaped env var to allow passing mutiple extra args via one env var (bash array vars cannot be passed via env vars); limitations: split on spaces will break any tentative of space escaping: space chars are not supported.
how to pass …

Add DMAKE_DOCKER_RUN_EXTRA_ARGS env var support

---

dmake/utils/dmake_replace_vars

Using dmake with python 3.12 fails with:
```
dmake.common.ShellError: /Users/vincent/deepomatic/dmake/dmake/utils/dmake_replace_vars:36: SyntaxWarning: invalid escape sequence '\$'
lvars = re.findall('\${([A-Za-z\-_]+)}', data)
```
This PR fixes it.

Fix escaped string for python3.12

---

Jenkinsfile
dmake/core.py
docs/USAGE.md

The [Code Coverage Plugin](https://plugins.jenkins.io/code-coverage-api/) is deprecated and does not work anymore.
We follow the instruction of the linked page and replace `publishCoverage` by `recordCoverage`.
This has been tested on Jenkins, it leads to the apparition of 2 menu entries below "Test result", that were not present before this PR:
The "Coverage report" looks like this:

Use supported coverage plugin
