Deepomatic/dmake

- deepomatic/dmake/core.py
- deepomatic/dmake/utils/dmake_find
- deepomatic/dmake/utils/dmake_md5
See #21 : the fix was extended to other calls to `find`
> Add full support for a robust 'find' command

- deepomatic/dmake/common.py
- deepomatic/dmake/core.py
- deepomatic/dmake/deepobuild.py
- deepomatic/dmake/serializer.py
**Do not merge before #28**.
Closes #31 
Currently supports specialized `env`, evaluated in the current DMake
file env context.
> Support multiple instances of needed_service per service_name

- deepomatic/dmake/common.py
- deepomatic/dmake/dmake
This now works on git worktrees too.
> Use git to find repository root path.

- deepomatic/dmake/deepobuild.py
- deepomatic/dmake/utils/dmake_deploy_kubernetes
> Kubernetes deployment

- deepomatic/dmake/common.py
> Revert "Add `DMAKE_PULL_CONFIG_DIR` environment variable option to optionally disable pulling env config dir"

- deepomatic/dmake/deepobuild.py
The substitution was previously done too late: after validation.
Now this works:
```
docker_links:
- image_name: postgres:9.6
link_name: db
volumes:
- "${MY_DB}/data:/var/lib/postgresql/data"
```
> Fix env var substitution in `docker_links` volumes definition

- deepomatic/dmake/deepobuild.py
- it's closer to the deployment this way
- it avoids permissions issues as `run` ignores `DMAKE_UID`, often
leading to root files in host
Now repository root volume is only mounted in shell and test.
`shell` needs to keep the volume mount, but maybe `test` should also stop mounting volume.
This PR could be reverted, but then we must use `DMAKE_UID` on run commands, to avoid existing permission issues.
> Stop mounting repository root volume in `run`

- deepomatic/dmake/core.py
- deepomatic/dmake/deepobuild.py
Currently, a service that:
- had no `deploy` configuration
- a default `config::docker_image::name` value 
led to dmake refusual to deploy.
This fixes it.
> Proper handling of services with no deploy

- deepomatic/dmake/deepobuild.py
Also add read_only option for the mounted volume.
> Allow host path on `tests.data_volumes`, for example to mount credentials from host

- deepomatic/dmake/utils/dmake_wait_for_it
(as long as they have an explicit port)
> dmake_wait_for_it: Add support for full URIs

- deepomatic/dmake/utils/dmake_copy
> add -L option when copying in dmake_copy

- deepomatic/dmake/deepobuild.py
This works only if base images are provided locally.
> Allow to run dmake without internet connection

- deepomatic/dmake/deepobuild.py
- deepomatic/dmake/utils/dmake_run_docker_link
- tutorial/worker/dmake.yml
- Add `env` to docker_links
- Cleanup escaping for docker links testing_options
> Docker links env

- deepomatic/dmake/core.py
- deepomatic/dmake/deepobuild.py
- deepomatic/dmake/utils/dmake_check_daemons
Closes #114 and hopefully numerous uncatched errors during dmake generated bash execution.
> Fix error check daemon

- deepomatic/dmake/deepobuild.py
- now support env var from runtime env in services `data_volumes`
- now support env var (including from runtime env) in docker links `testing_options`
- also support docker links `volumes` for `test` command (previously
only `shell` for unknown reason)
> volumes: more environment variable substitution

- deepomatic/dmake/utils/dmake_deploy_k8s_cd
- requirements.txt
Improve stability of the cluster
> Avoid deploying all pods at the same time

- deepomatic/dmake/templates/jenkins/Jenkinsfile
> Recursive submodules git checkout

- README.md
- docs/EXAMPLE.md
- docs/FORMAT.md
Updated doc by running `make` in `/docs` and manually patched README.md
> Updated docs and README

- dmake/common.py
One of the utilities was not python3 compatible.
> Fix use of dmake with python3

- dmake/deepobuild.py
- dmake/dmake
- dmake/docs.py
- dmake/serializer.py
- docs/EXAMPLE.md
- docs/FORMAT.md
Various fix and cleanup and improvements around auto-generated doc and example.
See commits logs for details, and `git diff -b` on `docs/`
> Better generated doc and example

- Jenkinsfile
- dmake/templates/jenkins/Jenkinsfile
- dmake/utils/dmake_build_base_docker
> Add option to force base image build, ignoring base image cache.

- dmake/common.py
- dmake/docker_config.py
- install.sh
Closes #202.
Also fixes issues introduced by #185 @vdel and various other cleanups.
> Global config file

- dmake/utils/dmake_md5
> Harmonize behaviour of repo digest computation between Linux and MacOS

- dmake/deepobuild.py
Cleanup `full_docker_opts(self, testing_mode)`: use explicit
parameters instead:
- `mount_host_volumes`: `True` for SSHDeploy only
- `use_host_ports`:
- `None` when users decides via global config:
- `dmake run`
- `dmake shell`
- `True` when SSHDeploy
- `False` when `dmake test`
> Never use host_ports when executing tests

- dmake/serializer.py
- requirements.txt
Bumping to ruamel.yaml==0.15.60 for Python 3.7 comptibility
> Bumping to newer version of ruamel.yaml for Python3.7 compatibility

- dmake/common.py
Followup on #248
- square boxes for nodes
- more readable node label
- group nodes by command
```
$ dmake --debug-graph-and-exit test '*'
===============                                                                                                                                                                                                                              
REPO : dmake                                                                                                                                                                                                                                 
BUILD : 0 …
```
> Cleaner debug graph

- dmake/deepobuild.py
- test/web/dmake.yml
> Allow no host_port on service ports: use random host port as if DMAKE_USE_HOST_PORTS=0

- dmake/deepobuild.py
Closes #300 
DMake executes services in 2 modes:
- dev (`dmake shell`)
- run (`dmake run`, `dmake test`)
In run mode:
- service v1: `WORKDIR` is always set in the dmake-generated Dockerfile
- service v2: we *do not* want --workdir there: it's the
responsibility of the user-provided Dockerfile
=> we need workdir only for dev mode.
> add `--workdir` to `docker run` only for `dmake shell`

- dmake/deepobuild.py
Closes #303 
Now they also accept an array of files paths in addition to the
previous unique string file path.
> Support multiple junit_report and cobertura_report files

- Jenkinsfile
> DMake own Jenkinsfile: Only run dmake self tests if testing dmake itself

- dmake/commands/release.py
I realized I had also fixed the release process (@maingoh)
Feel free to close it if you do not want/need to merge.
> Fix release process

- dmake/common.py
> Fix git remote detection when branch.<>.remote=.

- dmake/deepobuild.py
Closes #332.
It is retro-compatible in the sense that all previously working
substitutions still work: `${FOO}`
It now also allow:
- `$FOO` without `{` and `}`
- `$` escaping: `$$`
> Use Python PEP 292 as Template engine for kubernetes manifests

- dmake/common.py
- dmake/core.py
- dmake/dmake
- install.sh
- requirements.txt
Test with:
eval "$(register-python-argcomplete dmake)"
Also add `dmake completion` command and setup in install.sh.
> Add shell completion

- dmake/utils/dmake_deploy_kubernetes
Just apply the DMake `env` ConfigMap.
Also fix rollout watch: use correct context.
> Fix kubernetes deployment with no manifest

- dmake/utils/dmake_deploy_k8s_cd
- requirements.txt
This allows us to upgrade from ExtensionsV1beta1Api to AppsV1Api.
> Support multiple kubernetes API versions for Deployments in k8s_cd

- dmake/deepobuild.py
Closes #357.
Previously it was validated against a random default context which may
support different APIs.
> Validate kubernetes manifests against the correct kubectl context.

- dmake/utils/dmake_deploy_k8s_cd
> k8s_cd: Ignore Deployments that disappeared during loop patching

- dmake/core.py
When starting dmake, it's show the list of action it will follow.
Some actions turn to however be empty, especially when no tests are set for a service, or when you use an external image for a service (see #368, you do not expect a build step) which is a bit confusing for the user. This PR allow to show the "real" battle plan, once empty steps have been filtered out.
> Shows the real battle plan

- dmake/core.py
> Improve console output

- dmake/dmake
Use-case:
```
dmake run foo -b master
dmake stop -b master
```
> Support branch selection for `dmake stop` too

- dmake/templates/jenkins/Jenkinsfile
- Trigger rebuild using `/rebuild` command in a PR comment
- Jenkins dmake build: --dependencies is the default
- Add OVERRIDE_DMAKE_COMMAND (Related to #377)
> Jenkins: rebuild command

- dmake/core.py
> Keep all html reports, not just the last one

- dmake/common.py
`ruamel.yaml` uses version 1.2 by default, and emits version directive
when forced in 1.1 (`%YAML 1.1` header).
`kubectl` doesn't support explicit `%YAML 1.1` header, nor explicit or
even implicit 1.2, at least regarding the boolean literals issue, see
https://github.com/kubernetes/kubernetes/issues/34146
We now force 1.1 on `ruamel.yaml` and disable emitting the `%YAML 1.1`
version directive.
This fixes `'no'` as container env value in the kubernetes manifests.
Closes #401
> Force read and write YAML in version 1.1

- dmake/commands/release.py
> Fix release when starting a new major or minor with rc

- dmake/core.py
- dmake/deepobuild.py
- docs/EXAMPLE.md
- docs/FORMAT.md
The use of `blacklist`/`whitelist` is problematic (racially charged). 
I propose the use of `blocklist`/`allowlist`: no idea association with color and more explicit.
> Replace use of blacklist with blocklist

- dmake/deepobuild.py
> Fix _validate_ inheriance: use same arguments as parent method

- dmake/deepobuild.py
- test/gpu/dmake.yml
I needed to mount a physical device
> Minimal device support

- dmake/common.py
- dmake/core.py
Preparation work for jenkins parallel execution
> Jenkins code generation: Cleanup lock, add parallel

- README.md
- dmake/cli.py
- dmake/commands/__init__.py
- dmake/commands/generate_doc.py
- dmake/docs.py
- dmake/serializer.py
- docs/EXAMPLE.md
- docs/FORMAT.md
- docs/Makefile
- docs/USAGE.md
- docs/test_docs.py
TODO: rebase and merge after #472 merge (which changes the generated doc)
> Add dmake generate-doc command; fix doc generation; update doc; add dmake --help usage too

- test/worker/dmake.yml
- tutorial/worker/dmake.yml
3.7 is now unmaintained: https://github.com/docker-library/rabbitmq/pull/431
> Bump rabbitmq 3.8

- test/e2e/dmake.yml
- test/gpu/dmake.yml
test/ maintenance
Bump nginx to 1.20.2
Bump tensorflow 2.7.0
> Bump nginx and tensorflow

- dmake/common.py
- dmake/deepobuild.py
Add `dmake.deepomatic.com/deploy-username` attribute to k8s annotation generator
Closes #508
> Add k8s annotations with user info

- dmake/utils/dmake_deploy_kubernetes
> kubernetes argo rollouts wait: only if api-resource exists on cluster

- dmake/utils/dmake_deploy_kubernetes
> Rm desynced comment
